version: '3.8'

services:
  web:
    build: .
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - net

  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webchat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - net

networks:
  net:

volumes:
  db-data: